# Generated by Django 3.2.3 on 2022-07-14 14:30

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content_txt', models.TextField()),
                ('content_html', models.TextField()),
                ('receiver_person_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('receiver_email', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('sent', models.DateTimeField(null=True)),
                ('reference', models.CharField(db_index=True, max_length=100, null=True)),
                ('show_to_user', models.BooleanField(default=True)),
                ('read_by_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PollingSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_poll_requested', models.DateTimeField(auto_now_add=True)),
                ('app_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('template', ckeditor.fields.RichTextField()),
                ('format', models.CharField(choices=[('PLAIN', 'plain'), ('HTML', 'HTML'), ('PLAIN_HTML', 'plain_and_html')], max_length=15)),
                ('language', models.CharField(choices=[('fr-be', 'French'), ('en', 'English')], default='fr-be', max_length=30)),
            ],
            options={
                'unique_together': {('reference', 'language')},
            },
        ),
    ]
