# Generated by Django 3.2.3 on 2021-07-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountDeletionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('requested_at', models.DateField()),
                ('retry', models.SmallIntegerField(default=0)),
                ('error_payload', models.JSONField(default={})),
                ('app_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountRenewalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('requested_at', models.DateField()),
                ('retry', models.SmallIntegerField(default=0)),
                ('error_payload', models.JSONField(default={})),
                ('app_name', models.CharField(max_length=50)),
            ],
        ),
    ]
