# Generated by Django 3.2.3 on 2022-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_useraccountrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountrequest',
            name='type',
            field=models.CharField(choices=[('CREATION', 'CREATION'), ('DELETION', 'DELETION'), ('RENEWAL', 'RENEWAL')], max_length=50),
        ),
    ]
