# Generated by Django 3.2.3 on 2022-07-14 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_useraccountrequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccountrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
