# Generated by Django 3.2.3 on 2022-07-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220714_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountrequest',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
