# Generated by Django 3.2.3 on 2022-07-20 14:49

import base.models.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_useraccountrequest_email_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountrequest',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR'), ('PENDING', 'PENDING')], default=base.models.enum.UserAccountRequestStatus['PENDING'], max_length=50),
        ),
    ]
