# Generated by Django 3.2.3 on 2022-07-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_useraccountrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountrequest',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR'), ('PENDING', 'PENDING')], default='PENDING', max_length=50),
        ),
    ]
