# Generated by Django 3.2.3 on 2021-08-16 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210812_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountcreationrequest',
            name='person_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='useraccountdeletionrequest',
            name='person_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='useraccountrenewalrequest',
            name='person_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
