# Generated by Django 3.2.3 on 2025-05-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_userpasswordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountrequest',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR'), ('PENDING', 'PENDING'), ('DELETED', 'DELETED')], default='PENDING', max_length=50),
        ),
    ]
