# Generated by Django 3.2.3 on 2021-08-23 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_useraccountrequestresult_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingsubscriber',
            name='last_poll_requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccountrequestresult',
            name='app',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.pollingsubscriber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccountrequestresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
