# Generated by Django 3.2.3 on 2021-08-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210823_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountrequestresult',
            name='email',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
