# Generated by Django 3.2.3 on 2021-08-24 10:28
from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'messages_templates', app_label='base')


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_create_default_osis_registration_app_user'),
    ]

    operations = [
        migrations.RunPython(
            code=load_fixture,
            reverse_code=migrations.RunPython.noop
        )
    ]
