# Generated by Django 3.2.3 on 2022-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_load_initial_mail_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountcreationrequest',
            name='password',
            field=models.CharField(default='password', max_length=50),
            preserve_default=False,
        ),
    ]
