# Generated by Django 3.2.3 on 2022-07-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_useraccountcreationrequest_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountcreationrequest',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
