# Generated by Django 3.2.3 on 2021-07-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_registration', '0002_useraccountdeletionrequest_useraccountrenewalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountcreationrequest',
            name='account_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccountdeletionrequest',
            name='account_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccountrenewalrequest',
            name='account_renewed',
            field=models.BooleanField(default=False),
        ),
    ]
