# Generated by Django 3.2.3 on 2021-07-16 14:13

from django.db import migrations, models
import osis_registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_registration', '0002_useraccountdeletionrequest_useraccountrenewalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountRequestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_uuid', models.UUIDField(null=True)),
                ('request_type', models.CharField(choices=[(osis_registration.models.UserAccountCreationRequest, 'CREATION'), (osis_registration.models.UserAccountDeletionRequest, 'DELETION'), (osis_registration.models.UserAccountRenewalRequest, 'RENEWAL')], max_length=9)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('ERROR', 'SUCCESS')], max_length=7)),
            ],
        ),
        migrations.RenameField(
            model_name='useraccountcreationrequest',
            old_name='retry',
            new_name='attempt',
        ),
        migrations.RenameField(
            model_name='useraccountdeletionrequest',
            old_name='retry',
            new_name='attempt',
        ),
        migrations.RenameField(
            model_name='useraccountrenewalrequest',
            old_name='retry',
            new_name='attempt',
        ),
        migrations.RemoveField(
            model_name='useraccountdeletionrequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccountdeletionrequest',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='useraccountrenewalrequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccountrenewalrequest',
            name='last_name',
        ),
        migrations.AddField(
            model_name='useraccountcreationrequest',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='useraccountcreationrequest',
            name='person_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='useraccountcreationrequest',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccountcreationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraccountdeletionrequest',
            name='person_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='useraccountdeletionrequest',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccountdeletionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraccountrenewalrequest',
            name='person_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='useraccountrenewalrequest',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccountrenewalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='useraccountcreationrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useraccountdeletionrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useraccountrenewalrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
