# Generated by Django 3.2.3 on 2021-08-09 17:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_registration', '0003_auto_20210716_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountrequestresult',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR')], max_length=7),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('template', ckeditor.fields.RichTextField()),
                ('format', models.CharField(choices=[('PLAIN', 'plain'), ('HTML', 'HTML'), ('PLAIN_HTML', 'plain_and_html')], max_length=15)),
                ('language', models.CharField(choices=[('fr-be', 'French'), ('en', 'English')], default='fr-be', max_length=30)),
            ],
            options={
                'unique_together': {('reference', 'language')},
            },
        ),
    ]
