# Generated by Django 3.2.3 on 2021-07-14 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osis_registration', '0004_auto_20210714_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountRequestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_uuid', models.UUIDField()),
                ('request_type', models.CharField(choices=[('CREATION', 'CREATION'), ('DELETION', 'DELETION'), ('RENEWAL', 'RENEWAL')], max_length=9)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR')], max_length=7)),
            ],
        ),
        migrations.RenameField(
            model_name='useraccountcreationrequest',
            old_name='retry',
            new_name='attempt',
        ),
        migrations.RenameField(
            model_name='useraccountdeletionrequest',
            old_name='retry',
            new_name='attempt',
        ),
        migrations.RenameField(
            model_name='useraccountrenewalrequest',
            old_name='retry',
            new_name='attempt',
        ),
        migrations.RemoveField(
            model_name='useraccountcreationrequest',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='useraccountdeletionrequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccountdeletionrequest',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='useraccountdeletionrequest',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='useraccountrenewalrequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccountrenewalrequest',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='useraccountrenewalrequest',
            name='uuid',
        ),
        migrations.AddField(
            model_name='useraccountcreationrequest',
            name='person_uuid',
            field=models.UUIDField(default=uuid.UUID('e08845d5-9ad5-42bd-ad71-7431637768f4')),
        ),
        migrations.AddField(
            model_name='useraccountcreationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraccountdeletionrequest',
            name='person_uuid',
            field=models.UUIDField(default=uuid.UUID('87a9e42e-2f09-41df-bef3-4391aa2861db')),
        ),
        migrations.AddField(
            model_name='useraccountdeletionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraccountrenewalrequest',
            name='person_uuid',
            field=models.UUIDField(default=uuid.UUID('d472041e-3e3d-41d7-b5ca-f4e8fd2331ab')),
        ),
        migrations.AddField(
            model_name='useraccountrenewalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='useraccountcreationrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useraccountdeletionrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useraccountrenewalrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
