# Generated by Django 3.2.3 on 2021-07-14 12:08

from django.db import migrations, models
import osis_registration.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osis_registration', '0005_auto_20210714_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountcreationrequest',
            name='person_uuid',
            field=models.UUIDField(default=uuid.UUID('9377bfed-2e23-4668-9d7f-4961aa0338f1')),
        ),
        migrations.AlterField(
            model_name='useraccountdeletionrequest',
            name='person_uuid',
            field=models.UUIDField(default=uuid.UUID('454e4827-59f1-4fe7-92c1-018671ea967a')),
        ),
        migrations.AlterField(
            model_name='useraccountrenewalrequest',
            name='person_uuid',
            field=models.UUIDField(default=uuid.UUID('81eccfec-a46e-4876-af17-ebfe0d23a4f3')),
        ),
        migrations.AlterField(
            model_name='useraccountrequestresult',
            name='request_type',
            field=models.CharField(choices=[(osis_registration.models.UserAccountCreationRequest, 'CREATION'), (osis_registration.models.UserAccountDeletionRequest, 'DELETION'), (osis_registration.models.UserAccountRenewalRequest, 'RENEWAL')], max_length=9),
        ),
    ]
