# Generated by Django 3.2.3 on 2021-08-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_registration', '0005_messagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountcreationrequest',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
