# Generated by Django 3.2.3 on 2021-07-14 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osis_registration', '0006_auto_20210714_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccountcreationrequest',
            old_name='account_created',
            new_name='success',
        ),
        migrations.RenameField(
            model_name='useraccountdeletionrequest',
            old_name='account_deleted',
            new_name='success',
        ),
        migrations.RenameField(
            model_name='useraccountrenewalrequest',
            old_name='account_renewed',
            new_name='success',
        ),
        migrations.AlterField(
            model_name='useraccountcreationrequest',
            name='person_uuid',
            field=models.UUIDField(default=uuid.UUID('2ad2175a-0833-45d6-a331-a4838b592936')),
        ),
        migrations.AlterField(
            model_name='useraccountdeletionrequest',
            name='person_uuid',
            field=models.UUIDField(default=uuid.UUID('7a30cd21-acb7-4ba6-9c1f-3d59617439e5')),
        ),
        migrations.AlterField(
            model_name='useraccountrenewalrequest',
            name='person_uuid',
            field=models.UUIDField(default=uuid.UUID('a5f861ad-4867-43d4-9ad3-d4c0663dfa6d')),
        ),
    ]
