# Generated by Django 3.2.3 on 2021-08-19 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('osis_registration', '0008_auto_20210816_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountcreationrequest',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='useraccountdeletionrequest',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='useraccountrenewalrequest',
            name='app_name',
        ),
        migrations.CreateModel(
            name='PollingSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('app_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useraccountcreationrequest',
            name='app',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osis_registration.pollingsubscriber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccountdeletionrequest',
            name='app',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osis_registration.pollingsubscriber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccountrenewalrequest',
            name='app',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='osis_registration.pollingsubscriber'),
            preserve_default=False,
        ),
    ]
