openapi: 3.0.0
info:
  version: "1.0.0"
  title: OSIS-registration API
  description: 'This API delivers data for the OSIS-registration project.'
  contact:
    name: 'UCLouvain - OSIS'
    url: https://github.com/uclouvain/osis-registration

servers:
  - url: https://test.registration.osis.uclouvain.be/api/v1/
    description: Test server
  - url: https://registration.osis.uclouvain.be/api/v1/
    description: Production server

paths:
  /create_account:
    post:
      description: Create new user account creation request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAccountCreationRequest'
      responses:
        201:
          description: Successfully created an user account creation request
      tags:
        - osis-registration
  /delete_account:
    post:
      description: Create new user account deletion request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAccountDeletionRequest'
      responses:
        200:
          description: Successfully created an user account deletion request
      tags:
        - osis-registration
  /renew_account:
    post:
      description: Create new user account renewal request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAccountRenewalRequest'
      responses:
        200:
          description: Successfully created an user account renewal request
      tags:
        - osis-registration
components:
  securitySchemes:
    Token:
      type: apiKey
      in: header
      name: Authorization
      description: Enter your token in the format **Token &lt;token>**

  schemas:
    UserAccountCreationRequest:
      type: object
      properties:
          first_name:
            type: string
            example: "John"
          last_name:
            type: string
            example: "Doe"
          birth_date:
            type: string
            example: "1989-01-01"
          email:
            type: string
            example: "john.doe@mail.xyz"
          password:
            type: string
            format: password
    UserAccountDeletionRequest:
      type: object
      properties:
          email:
            type: string
            example: "john.doe@mail.xyz"
    UserAccountRenewalRequest:
      type: object
      properties:
          email:
            type: string
            example: "john.doe@mail.xyz"
          validity_days:
            type: number
            example: 365

security:
  - Token: []
